config/routes.rb
Rails.application.routes.draw do
  resources :products do
    member do
      post :add_cart
      post :remove_cart
      post :delete_cart
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'
  get '/show-all' => 'products#show_all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product

  def self.total_price
    sum = 0
    Cart.all.each do|c|
      sum += c.quality * c.product.price
    end
    sum
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :cart

  validates :name, :description, :image, :color, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    @carts = Product.where(id: Cart.pluck(:product_id))
    @total_price = Cart.total_price
    
    p "!!!!!!!!!!! @total_price:"
    p  @total_price
  end

  def add_cart
    # p "params"
    # p params
    @product = Product.find(params[:id])
    @cart = @product.cart

    if @cart.nil?
      @cart = Cart.create({product_id: @product.id, quality: 1})
      @product.reload
    else
      @cart.quality += 1
      @cart.save
      p "qauuuly"
      p @cart.quality
    end
    @total_price = Cart.total_price
  end

  def remove_cart
    p "dele params"
    p params
    @product = Product.find(params[:id])
    @cart = @product.cart
    if @cart.quality > 1
      @cart.quality -= 1
      @cart.save
    else
      @cart.destroy
      @cart.save
      @cart = nil
    end
    @total_price = Cart.total_price
    @current_cart = Cart.all
  end

  def delete_cart
    @product = Product.find(params[:id])
    @cart = @product.cart.destroy
    @cart.save
    @cart = nil
    @total_price = Cart.total_price
    @current_cart = Cart.all
  end

  def show_all
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InternApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_item_cart.html.erb
 <div class="cart-item" id="cart_item_id_<%=productC.id%>">
  <div class="cart-container">
    <div class="cart-image">
      <div class="image-background" style="background-color:<%=productC.color%>"> 
        <%= image_tag productC.image, class: "cimg"%>
      </div> 
    </div>
    <div class="cart-content">
      <p class="cart-name">
        <%= productC.name%>
      </p>
      <p class="cart-price">
        <%= number_to_currency(productC.price) %>
      </p>
      <div class="cart-actions">
        <div class="cart-edit">

          <%= link_to remove_cart_product_path(productC), method: :post, remote: true do %>
            <button class="cart-btn" >
              <%= image_tag "minus.png", class: "aimg"%>
            </button>
          <% end %>
      
          <p class="cart-amout" style="margin-right: 10px;" id="item_quality_<%=productC.id%>"><%= productC.cart.quality%></p>

          <%= link_to add_cart_product_path(productC), method: :post, remote: true do %>
            <button class="cart-btn">
              <%= image_tag "plus.png", class: "aimg"%>
            </button>
          <% end %>
          
        </div>

        <%= link_to delete_cart_product_path(productC), method: :post, remote: true do %>
          <button class="dele-btn" style="background-color: #f6c90e">
            <%= image_tag "trash.png", class: "timg"%>
          </button>
        <% end %>

      </div>                
    </div>
  </div>
</div>

app/views/products/_item_product.html.erb
       
<div class="item">
  <% @products.each do |product| %>
    <div class="item-body">
      <div class="prodimg" style="background-color:<%=product.color%>">
        <%= image_tag product.image, class: "pimg"%>
      </div>
      <div class="proddes">
        <p class="name">
          <%= product.name%>
        </p>
        <p class="descriptions">
          <%= product.description%>
        </p>
        <div class="acct">
          <p class="price">
            $<%=product.price%>
          </p>
          <div id="product_action_<%=product.id%>">
            <%= render partial: 'products/product_action', locals: {product: product}%>
          </div>
        </div>
      </div>  
    </div>
  <%end%>
</div>

app/views/products/_product_action.html.erb
          
<%if !product.cart.present? %>
  <button class="add-cart" id="add-btn_<%=product.id%>">
  <%= link_to "ADD TO CARD", add_cart_product_path(product), method: :post, remote: true %>
  </button>
<% else %>
  <div class="check-item" id="check-btn_<%=product.id%>">
      <%= image_tag "check.png", class: "pcheck"%>
  </div>
<%end%>

app/views/products/add_cart.js.erb
$('#emptyNoti').hide();
$("#product_action_<%= @product.id%>").html(
   "<%= escape_javascript(render(partial: 'product_action', locals: {product: @product})) %>"
  )
<%if @cart.quality == 1 %>

  $('#list_carts').append(
    "<%= escape_javascript(render(partial: 'item_cart', locals: {productC: @product})) %>"
  );
<%else%>
  $("#item_quality_<%= @product.id %>").html("<%=@cart.quality%>");
<%end%>
$('#total_price_cart').html("<%= number_to_currency(@total_price)%>")

app/views/products/delete_cart.js.erb
$('#total_price_cart').html("<%= number_to_currency(@total_price)%>")

<%if @cart.nil? %>
  $("#cart_item_id_<%= @product.id%>").remove();
  $("#product_action_<%= @product.id%>").html(
   "<%= escape_javascript(render(partial: 'product_action', locals: {product: @product.reload})) %>"
  )
<%end%>
<%if @current_cart.empty? %>
  $('#emptyNoti').show();
<%end%>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="my-body">
  <div class="head-action">
    <%= link_to 'New Product', new_product_path, style: "color: green" %>
    <%= link_to 'Show Product', show_all_path %>
  </div>

  <div class="container">
    <div class="list">
      <div class="header">
        <%= image_tag 'nike.png', class: "nikeico"%>
        <p class="cart-title">Our Products</p>
      </div>
      <div class="list-items">
        <%= render partial: 'products/item_product'%>
      </div>  
    </div>
    <div class="list">
      <div class="cart-header">
        <%= image_tag 'nike.png', class: "nikeico"%>
        <div class="title"> 
          <p class="cart-title" >Your Cart</p>
          <p class="cart-title" id="total_price_cart"><%= number_to_currency(@total_price)%></p>
        </div>
      </div>
      <div class="content"></div>
        <div class="list-cart" id="list_carts">
          <% @carts.each do |cart| %>
            <%= render partial: 'products/item_cart', locals: {productC: cart} %>
          <% end %>

          <%if @carts.empty?%>
            <p class="descriptions" id="emptyNoti">Your cart is empty</p>
          <%end%>
          
        </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/remove_cart.js.erb
$('#total_price_cart').html("<%= number_to_currency(@total_price)%>")
<%if @cart.nil? %>
  $("#cart_item_id_<%= @product.id%>").remove();
  $("#product_action_<%= @product.id%>").html(
   "<%= escape_javascript(render(partial: 'product_action', locals: {product: @product.reload})) %>"
  )
<%else%>
  $('#item_quality_<%=@product.id%>').html("<%= @cart.quality%>")
<%end%>
<%if @current_cart.empty? %>
  $('#emptyNoti').show();
<%end%>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/show_all.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<%= link_to 'Back to Cart', root_path, style: "color: red" %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.image %></td>
        <td><%= product.color %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>